/** Static path redirects (301). Keys are pathname without query/hash. */
export const PATH_REDIRECTS = new Map([
  ['/go/dota-2', '/go/rainbow-six-siege/'],
  ['/go/dota-2/', '/go/rainbow-six-siege/'],
  ['/forums', '/forums/'],
  ['/blog', '/forums/'],
  ['/blog/', '/forums/'],
  ['/cheats', '/cheats/'],
  ['/about', '/about/'],
  ['/contact', '/contact/'],
  ['/privacy', '/privacy/'],
  ['/faq', '/faq/'],
  // Legacy product path migration → tools
  ['/products/dota-2-cheats', '/tools/r6s-cheats/'],
  ['/products/dota-2-cheats/', '/tools/r6s-cheats/'],
  ['/products/dota-2-cheats/account-recovery', '/tools/r6s-cheats/ugc/'],
  ['/products/dota-2-cheats/account-recovery/', '/tools/r6s-cheats/ugc/'],
  ['/products/dota-2-cheats/lite', '/tools/r6s-cheats/lite/'],
  ['/products/dota-2-cheats/lite/', '/tools/r6s-cheats/lite/'],
  ['/products/dota-2-cheats/pro', '/tools/r6s-cheats/pro/'],
  ['/products/dota-2-cheats/pro/', '/tools/r6s-cheats/pro/'],
  ['/products/dota-2-cheats/elite', '/tools/r6s-cheats/elite/'],
  ['/products/dota-2-cheats/elite/', '/tools/r6s-cheats/elite/'],
  ['/products/dota-2-cheats/hwid-spoofer', '/tools/r6s-cheats/hwid-spoofer/'],
  ['/products/dota-2-cheats/hwid-spoofer/', '/tools/r6s-cheats/hwid-spoofer/'],
  ['/products/dota-2-cheats/unlock-all', '/tools/r6s-cheats/unlock-all/'],
  ['/products/dota-2-cheats/unlock-all/', '/tools/r6s-cheats/unlock-all/'],
  ['/products/dota-2-cheats/ugc', '/tools/r6s-cheats/ugc/'],
  ['/products/dota-2-cheats/ugc/', '/tools/r6s-cheats/ugc/'],
  ['/products/r6s-cheats', '/tools/r6s-cheats/'],
  ['/products/r6s-cheats/', '/tools/r6s-cheats/'],
  ['/products/r6s-cheats/lite', '/tools/r6s-cheats/lite/'],
  ['/products/r6s-cheats/lite/', '/tools/r6s-cheats/lite/'],
  ['/products/r6s-cheats/pro', '/tools/r6s-cheats/pro/'],
  ['/products/r6s-cheats/pro/', '/tools/r6s-cheats/pro/'],
  ['/products/r6s-cheats/elite', '/tools/r6s-cheats/elite/'],
  ['/products/r6s-cheats/elite/', '/tools/r6s-cheats/elite/'],
  ['/products/r6s-cheats/hwid-spoofer', '/tools/r6s-cheats/hwid-spoofer/'],
  ['/products/r6s-cheats/hwid-spoofer/', '/tools/r6s-cheats/hwid-spoofer/'],
  ['/products/r6s-cheats/unlock-all', '/tools/r6s-cheats/unlock-all/'],
  ['/products/r6s-cheats/unlock-all/', '/tools/r6s-cheats/unlock-all/'],
  ['/products/r6s-cheats/ugc', '/tools/r6s-cheats/ugc/'],
  ['/products/r6s-cheats/ugc/', '/tools/r6s-cheats/ugc/'],
  // Legacy blog slug migration → forums (WarDogs-style thread slugs)
  ['/blog/dota-2-cheat-codes-guide', '/forums/how-to-use-r6s-cheats/'],
  ['/blog/dota-2-cheat-codes-guide/', '/forums/how-to-use-r6s-cheats/'],
  ['/blog/dota-2-console-cheats-tips', '/forums/how-to-use-r6s-cheats/'],
  ['/blog/dota-2-console-cheats-tips/', '/forums/how-to-use-r6s-cheats/'],
  ['/blog/how-to-use-dota-2-cheat-codes', '/forums/how-to-use-r6s-cheats/'],
  ['/blog/how-to-use-dota-2-cheat-codes/', '/forums/how-to-use-r6s-cheats/'],
  ['/blog/dota-2-cheats-features-guide', '/forums/r6s-cheat-menu-guide/'],
  ['/blog/dota-2-cheats-features-guide/', '/forums/r6s-cheat-menu-guide/'],
  ['/blog/dota-2-console-commands-cheats', '/forums/how-to-use-r6s-cheats/'],
  ['/blog/dota-2-console-commands-cheats/', '/forums/how-to-use-r6s-cheats/'],
  ['/blog/dota-2-lite-vs-pro', '/forums/r6s-cheat-menu-guide/'],
  ['/blog/dota-2-lite-vs-pro/', '/forums/r6s-cheat-menu-guide/'],
  ['/blog/dota-2-elite-tier-guide', '/forums/r6s-cheat-menu-guide/'],
  ['/blog/dota-2-elite-tier-guide/', '/forums/r6s-cheat-menu-guide/'],
  ['/blog/dota-2-scripts-ranked-mmr', '/forums/r6s-soft-aim-settings/'],
  ['/blog/dota-2-scripts-ranked-mmr/', '/forums/r6s-soft-aim-settings/'],
  ['/blog/dota-2-map-hack-setup', '/forums/r6s-esp-settings/'],
  ['/blog/dota-2-map-hack-setup/', '/forums/r6s-esp-settings/'],
  ['/blog/dota-2-zoom-hack-guide', '/forums/r6s-soft-aim-settings/'],
  ['/blog/dota-2-zoom-hack-guide/', '/forums/r6s-soft-aim-settings/'],
  ['/blog/dota-2-skin-changer-guide', '/forums/r6s-cheat-menu-guide/'],
  ['/blog/dota-2-skin-changer-guide/', '/forums/r6s-cheat-menu-guide/'],
  ['/blog/vac-patch-day-checklist', '/forums/r6s-patch-rebuild-guide/'],
  ['/blog/vac-patch-day-checklist/', '/forums/r6s-patch-rebuild-guide/'],
  ['/blog/dota-2-hwid-spoofer-after-ban', '/forums/r6s-loader-errors/'],
  ['/blog/dota-2-hwid-spoofer-after-ban/', '/forums/r6s-loader-errors/'],
  ['/blog/how-to-buy-dota-2-cheats-2026', '/forums/r6s-cheat-setup/'],
  ['/blog/how-to-buy-dota-2-cheats-2026/', '/forums/r6s-cheat-setup/'],
  ['/blog/dota-2-auto-combo-hero-scripts', '/forums/r6s-soft-aim-settings/'],
  ['/blog/dota-2-auto-combo-hero-scripts/', '/forums/r6s-soft-aim-settings/'],
  ['/blog/valve-anti-cheat-unable-to-verify', '/forums/r6s-loader-errors/'],
  ['/blog/valve-anti-cheat-unable-to-verify/', '/forums/r6s-loader-errors/'],
  ['/blog/dota-2-external-cheat-guide', '/forums/r6s-cheat-setup/'],
  ['/blog/dota-2-external-cheat-guide/', '/forums/r6s-cheat-setup/'],
  ['/blog/dota-2-stream-proof-setup', '/forums/r6s-esp-settings/'],
  ['/blog/dota-2-stream-proof-setup/', '/forums/r6s-esp-settings/'],
  // Prior R6S forum slugs → WarDogs-style thread slugs
  ['/forums/r6s-cheat-codes-guide', '/forums/how-to-use-r6s-cheats/'],
  ['/forums/r6s-cheat-codes-guide/', '/forums/how-to-use-r6s-cheats/'],
  ['/forums/r6s-console-cheats-tips', '/forums/how-to-use-r6s-cheats/'],
  ['/forums/r6s-console-cheats-tips/', '/forums/how-to-use-r6s-cheats/'],
  ['/forums/how-to-use-r6s-cheat-codes', '/forums/how-to-use-r6s-cheats/'],
  ['/forums/how-to-use-r6s-cheat-codes/', '/forums/how-to-use-r6s-cheats/'],
  ['/forums/r6s-cheats-features-guide', '/forums/r6s-cheat-menu-guide/'],
  ['/forums/r6s-cheats-features-guide/', '/forums/r6s-cheat-menu-guide/'],
  ['/forums/r6s-console-commands-cheats', '/forums/how-to-use-r6s-cheats/'],
  ['/forums/r6s-console-commands-cheats/', '/forums/how-to-use-r6s-cheats/'],
  ['/forums/r6s-lite-vs-pro', '/forums/r6s-cheat-menu-guide/'],
  ['/forums/r6s-lite-vs-pro/', '/forums/r6s-cheat-menu-guide/'],
  ['/forums/r6s-elite-tier-guide', '/forums/r6s-cheat-menu-guide/'],
  ['/forums/r6s-elite-tier-guide/', '/forums/r6s-cheat-menu-guide/'],
  ['/forums/r6s-aimbot-ranked-setup', '/forums/r6s-soft-aim-settings/'],
  ['/forums/r6s-aimbot-ranked-setup/', '/forums/r6s-soft-aim-settings/'],
  ['/forums/r6s-esp-setup', '/forums/r6s-esp-settings/'],
  ['/forums/r6s-esp-setup/', '/forums/r6s-esp-settings/'],
  ['/forums/r6s-no-recoil-guide', '/forums/r6s-soft-aim-settings/'],
  ['/forums/r6s-no-recoil-guide/', '/forums/r6s-soft-aim-settings/'],
  ['/forums/r6s-unlock-all-operators', '/forums/r6s-cheat-menu-guide/'],
  ['/forums/r6s-unlock-all-operators/', '/forums/r6s-cheat-menu-guide/'],
  ['/forums/battleye-patch-day-checklist', '/forums/r6s-patch-rebuild-guide/'],
  ['/forums/battleye-patch-day-checklist/', '/forums/r6s-patch-rebuild-guide/'],
  ['/forums/r6s-hwid-spoofer-after-ban', '/forums/r6s-loader-errors/'],
  ['/forums/r6s-hwid-spoofer-after-ban/', '/forums/r6s-loader-errors/'],
  ['/forums/how-to-buy-r6s-cheats-2026', '/forums/r6s-cheat-setup/'],
  ['/forums/how-to-buy-r6s-cheats-2026/', '/forums/r6s-cheat-setup/'],
  ['/forums/r6s-aimbot-operator-configs', '/forums/r6s-soft-aim-settings/'],
  ['/forums/r6s-aimbot-operator-configs/', '/forums/r6s-soft-aim-settings/'],
  ['/forums/battleye-unable-to-verify', '/forums/r6s-loader-errors/'],
  ['/forums/battleye-unable-to-verify/', '/forums/r6s-loader-errors/'],
  ['/forums/r6s-external-cheat-guide', '/forums/r6s-cheat-setup/'],
  ['/forums/r6s-external-cheat-guide/', '/forums/r6s-cheat-setup/'],
  ['/forums/r6s-stream-proof-setup', '/forums/r6s-esp-settings/'],
  ['/forums/r6s-stream-proof-setup/', '/forums/r6s-esp-settings/'],
]);

/** Paths that should not receive a forced trailing slash. */
export const TRAILING_SLASH_SKIP = /\.[a-z0-9]+$/i;

export function resolvePathRedirect(pathname) {
  const direct = PATH_REDIRECTS.get(pathname);
  if (direct) return direct;

  if (pathname.startsWith('/blog/')) {
    const suffix = pathname.slice(5);
    return suffix.endsWith('/') ? `/forums${suffix}` : `/forums${suffix}/`;
  }

  if (pathname !== '/' && !pathname.endsWith('/') && !TRAILING_SLASH_SKIP.test(pathname)) {
    return `${pathname}/`;
  }

  return null;
}
